version: "3.7"

services: 

    service_1:
        image: sdhalliday92/service_1
        networks: 
            - sfia2_network
        depends_on: 
            - service_4
            - service_2
            - service_3
        deploy: 
            replicas: 2

    service_2:
        image: sdhalliday92/service_2
        networks: 
            - sfia2_network
        deploy: 
            replicas: 2
    
    service_3:
        image: sdhalliday92/service_3
        networks: 
            - sfia2_network
        deploy: 
            replicas: 2

    service_4:
        image: sdhalliday92/service_4
        networks: 
            - sfia2_network
        deploy: 
            replicas: 2

networks: 
    sfia2_network:
        driver: overlay

