---
    - name: Install Docker-CE on Manager
    hosts: localhost
    connection: local
    become: true
    roles:
      - docker-installation
      - docker-swarm-init

    - name: Install Docker-CE on worker
      hosts: swarm-worker
      become: true
      roles: 
        - docker-installation
    
    - name: Add worker to Manager
      hosts: swarm-worker
      become: true
      roles:
        - docker-add-swarm
