---
- name: Install Docker-CE on worker
  hosts: swarm-worker
  become: true
  roles: 
    - docker-installation
    
- name: Install Docker-CE on Manager
  hosts: sfia2
  connection: local
  become: true
  roles:
    - docker-installation
    - docker-swarm-init

- name: Add worker to Manager
  hosts: swarm-worker
  become: true
  roles:
    - docker-add-swarm
